version: '3.5'

services:

    nginx:
      image: ${COMPOSE_PROJECT_NAME}-nginx:latest
      build:
        context: ./docker/
        args:
          BUILD_ARGUMENT_ENV: dev
        dockerfile: ./nginx/Dockerfile
      container_name: ${COMPOSE_PROJECT_NAME}-nginx
      restart: always
      ports:
        - "${WEB_PORT_HTTP}:80"
        - "${WEB_PORT_SSL}:443"
      volumes:
        - .:/var/www/html:ro,cached
      depends_on:
        - laravel
      networks:
        - laravel

    laravel: &laravel-template
      image: ${COMPOSE_PROJECT_NAME}-laravel:latest
      build:
        context: .
        args:
          BUILD_ARGUMENT_ENV: dev
          HOST_UID: ${HOST_UID}
          HOST_GID: ${HOST_GID}
          XDEBUG_CONFIG: ${XDEBUG_CONFIG}
        dockerfile: ./Dockerfile
      container_name: ${COMPOSE_PROJECT_NAME}-laravel
      volumes:
        - .:/var/www/html:cached
      depends_on:
        - postgres
      networks:
        - laravel

    ### Cron tasks
    supervisord:
      <<: *laravel-template
      container_name: ${COMPOSE_PROJECT_NAME}-supervisord
      expose: []
      command: ["/usr/bin/supervisord"]

    postgres:
      container_name: ${COMPOSE_PROJECT_NAME}-postgres
      image: postgres
      environment:
        POSTGRES_USER: ${DB_USERNAME:-postgres}
        POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme}
        PGDATA: /data/postgres
      volumes:
        - postgres:/data/postgres
      ports:
        - "5432:5432"
      networks:
        - laravel
      restart: unless-stopped

    pgadmin:
      container_name: pgadmin_container
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
        PGADMIN_CONFIG_SERVER_MODE: 'False'
      volumes:
        - pgadmin:/var/lib/pgadmin

      ports:
        - "${PGADMIN_PORT:-5050}:80"
      networks:
        - laravel
      restart: unless-stopped

volumes:
  postgres:
  pgadmin:

networks:
  laravel:
    name: laravel
    driver: bridge
