name: Confit App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [published]

env:
  CONTAINER_NAME: "confit-app"
  DEPLOYMENT_PATH: "/opt/confit"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkkout master
        uses: actions/checkout@v2

      - name: Adding ssh-agent
        run: eval $(ssh-agent -s)

      - name: Adding ssh-key
        run: echo ${{ secrets.SSHKEY }} | tr -d '\r' | ssh-add -

      - name: Rsync
        run: rsync -rlpcvz --no-p -e ssh ${{ secrets.USERNAME }}@${{ secrets.DEPLOYMENT_HOST }}:$(echo $DEPLOYMENT_PATH)

      - name: copy env
        run: ssh ${{ secrets.USERNAME }}@${{ secrets.DEPLOYMENT_HOST }} "cd $(echo $DEPLOYMENT_PATH) && sudo cp .env.test .env"

      - name: check files
        run: ssh ${{ secrets.USERNAME }}@${{ secrets.DEPLOYMENT_HOST }} "cd $(echo $DEPLOYMENT_PATH) && ls"
#            - name: Build the docker images
#              run: make build-test
#            - name: Start the docker images
#              run: make start-test
#            - name: Check running containers
#              run: docker ps -a
#            - name: Wait for database connection
#              run: make wait-for-db
#            - name: Run migrations
#              run: make drop-migrate
#            - name: Run seeds
#              run: make seed
#            - name: Run test suite
#              run: make phpunit
#            - name: Run PHP coding standard
#              run: make ecs
#            - name: Run PHP codeSniffer
#              run: make phpcs
#            - name: Run PHP copy/paste detector
#              run: make phpcpd
#            - name: Run PHP mess detector
#              run: make phpmd
#            - name: Run PHPStan static analysis tool
#              run: make phpstan
#            - name: Run Phpinsights PHP quality checks
#              run: make phpinsights
#            - name: Stop the docker images
#              run: make stop-test
