name: Confit App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DEPLOYMENT_PATH: "/opt/confit-monolith"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy via SSH action
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOYMENT_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          envs: DEPLOYMENT_PATH
          script: |
            cd $(echo $DEPLOYMENT_PATH)
            git pull
            cp .env.test .env
            # stop running and remove old containers
            make stop-test
            # build containers
            make build-test
            # start containers
            make start-test
#            - name: Build the docker images
#              run: make build-test
#            - name: Start the docker images
#              run: make start-test
#            - name: Check running containers
#              run: docker ps -a
#            - name: Wait for database connection
#              run: make wait-for-db
#            - name: Run migrations
#              run: make drop-migrate
#            - name: Run seeds
#              run: make seed
#            - name: Run test suite
#              run: make phpunit
#            - name: Run PHP coding standard
#              run: make ecs
#            - name: Run PHP codeSniffer
#              run: make phpcs
#            - name: Run PHP copy/paste detector
#              run: make phpcpd
#            - name: Run PHP mess detector
#              run: make phpmd
#            - name: Run PHPStan static analysis tool
#              run: make phpstan
#            - name: Run Phpinsights PHP quality checks
#              run: make phpinsights
#            - name: Stop the docker images
#              run: make stop-test
